# Generated by Django 4.1 on 2022-08-11 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_inicio', models.DateTimeField(auto_now_add=True, null=True)),
                ('registro_fin', models.DateTimeField(auto_now_add=True, null=True)),
                ('propuesta_inicio', models.DateTimeField(auto_now_add=True, null=True)),
                ('propuesta_fin', models.DateTimeField(auto_now_add=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DemoRJ.person')),
            ],
        ),
    ]
